theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
isHTML = true
mediaType = "text/html"

[params.reveal_hugo]
#highlight_theme = "solarized-dark"
slide_number = true
theme = "solarized"
transition = "zoom"
