theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
isHTML = true
mediaType = "text/html"

[params.reveal_hugo]
#highlight_theme = "solarized-dark"
slide_number = true
theme = "solarized"
transition = "zoom"

[[deployment.targets]]
URL = "s3://hiq-workshop?region=eu-north-1"
name = "hiqdemo.com"

[[deployment.matchers]]
cacheControl = "max-age=600, no-transform, public"
gzip = true
pattern = "^.+\\.(js|css|svg|ttf)$"

[[deployment.matchers]]
cacheControl = "max-age=600, no-transform, public"
gzip = false
pattern = "^.+\\.(png|jpg)$"

[[deployment.matchers]]
contentType = "application/xml"
gzip = true
pattern = "^sitemap\\.xml$"

[[deployment.matchers]]
cacheControl = "max-age=0, no-transform, public"
gzip = true
pattern = "^.+\\.(html|xml|json)$"
