name: hiqdemo.com
on: push
jobs:
  hugo_deploy:
    env:
      HUGO_VERSION: 0.103.0
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download hugo
        uses: actions/cache@v3.0.8
        id: utils-cache
        with:
          path: |
            ./*.deb
          key: cache-${{ env.HUGO_VERSION }}
      - name: Install hugo
        run: |
          wget -c -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ./hugo_extended_${HUGO_VERSION}_linux-amd64.deb
      - name: "Login to AWS"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy
        run: |
          hugo && hugo deploy
